### ISSUE TITLE
为何不使用IPC而选择TCP？

### ISSUE THREAD

**Issue by Catlite91** [node-modules/cluster-client#35]
RT

**Comment by Catlite91** [comment]
thx！

**Comment by Catlite91** [comment]
所以其实是为了解决master频繁转发通信的问题？是否可以：
初始化时区分master和workers，以master为server建立竞争服务器
从workers中由master选出leader并通知其余workers
leader建立ipc server，workers连接leader，workers与leader通过ipc直连

**Comment by atian25** [comment]
> 另外，通过 messenger 传递数据效率是比较低的，因为它会通过 Master 来做中转；万一 IPC 通道出现问题还可能将 Master 进程搞挂。

egg 里面同时支持 2 种方式的，用于不同的场合，这个库是为 egg 那边服务的，IPC 的方式在 egg-cluster 里面。

**Comment by atian25** [comment]
具体的由作者 @gxcsoccer 来回答吧

**Comment by Catlite91** [comment]
所以master只在初始化时做中转，一旦leader选举成功，workers和leader也是直连
总觉得用tcp太重了

**Comment by gxcsoccer** [comment]
实际经验 IPC 的性能不如 tcp，另外后面我考虑用 unix domain socket 替换 socket

**Comment by wv1124** [comment]
为了fork？
