### ISSUE TITLE
是否可以考虑一下egg-logger版本的兼容性

### ISSUE THREAD

**Issue by ygmpkk** [node-modules/cluster-client#68]
Hello，最近的一次版本升级把 `egg-logger` 从 `2.23.2` 升级到了 `3.5.0`，这个会导致nodejs 12及其以下的版本出现这个报错：

```
...node_modules/cluster-client/node_modules/egg-logger/lib/utils.js:38

[egg-scripts]     const traceId = ctx.tracer?.traceId || '-';
[egg-scripts]                                ^
[egg-scripts] 
[egg-scripts] SyntaxError: Unexpected token '.'
[egg-scripts]     at wrapSafe (internal/modules/cjs/loader.js:931:16)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:979:27)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[egg-scripts]     at Module.load (internal/modules/cjs/loader.js:879:32)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:903:19)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:74:18)
```

@fengmk2

**Comment by fengmk2** [comment]
https://github.com/node-modules/cluster-client/blob/master/package.json#L58

cluster-client 只支持 node >= 14

**Comment by Rock-Legend** [comment]
@fengmk2 node升级到 14.0.0 也不行，执行启动，会报如下错误
`[egg-scripts] Got error when startup: 
[egg-scripts] internal/modules/cjs/loader.js:1017
[egg-scripts]   throw err;
[egg-scripts]   ^
[egg-scripts] 
[egg-scripts] Error: Cannot find module 'node:crypto'
[egg-scripts] Require stack:
[egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/crypto.js
[egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/index.js
[egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/utils.js
[egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/logger.js
[egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/index.js
[egg-scripts] - /node_modules/cluster-client/lib/default_logger.js
[egg-scripts] - /node_modules/cluster-client/lib/index.js
[egg-scripts] - /node_modules/cluster-client/index.js
[egg-scripts] - /node_modules/egg/lib/application.js
[egg-scripts] - /node_modules/egg/index.js

按照报错显示， cluster-client 依赖的第三方库 utility 2.1.0 版本需要  node >= 16.0.0
https://github.com/node-modules/utility/blob/master/package.json

将node版本升级到16.0.0 启动成功了

**Comment by tianyongheng** [comment]
我在部署eggjs时也遇到相同问题了，ci/cd系统构建镜像里node最高版本只有10.15。还有只有升级node这唯一方式吗，担心升级后会出现其他问题😓

**Comment by tianyongheng** [comment]
> @fengmk2 node升级到 14.0.0 也不行，执行启动，会报如下错误
> 
> `[egg-scripts] Got error when startup: [egg-scripts] internal/modules/cjs/loader.js:1017 [egg-scripts] throw err; [egg-scripts] ^ [egg-scripts] [egg-scripts] Error: Cannot find module 'node:crypto' [egg-scripts] Require stack: [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/crypto.js [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/index.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/utils.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/logger.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/index.js [egg-scripts] - /node_modules/cluster-client/lib/default_logger.js [egg-scripts] - /node_modules/cluster-client/lib/index.js [egg-scripts] - /node_modules/cluster-client/index.js [egg-scripts] - /node_modules/egg/lib/application.js [egg-scripts] - /node_modules/egg/index.js `
> 
> 按照报错显示， cluster-client 依赖的第三方库 utility 2.1.0 版本需要 node >= 16.0.0 https://github.com/node-modules/utility/blob/master/package.json
> 
> 将node版本升级到16.0.0 启动成功了

吐槽下：毫无预期管理，egg2.x版本只要求了node>8.5就行了，结果这又来了个node>=14?16😓

**Comment by fengmk2** [comment]
> @fengmk2 node升级到 14.0.0 也不行，执行启动，会报如下错误
> 
> `[egg-scripts] Got error when startup: [egg-scripts] internal/modules/cjs/loader.js:1017 [egg-scripts] throw err; [egg-scripts] ^ [egg-scripts] [egg-scripts] Error: Cannot find module 'node:crypto' [egg-scripts] Require stack: [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/crypto.js [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/index.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/utils.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/logger.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/index.js [egg-scripts] - /node_modules/cluster-client/lib/default_logger.js [egg-scripts] - /node_modules/cluster-client/lib/index.js [egg-scripts] - /node_modules/cluster-client/index.js [egg-scripts] - /node_modules/egg/lib/application.js [egg-scripts] - /node_modules/egg/index.js `
> 
> 按照报错显示， cluster-client 依赖的第三方库 utility 2.1.0 版本需要 node >= 16.0.0 https://github.com/node-modules/utility/blob/master/package.json
> 
> 将node版本升级到16.0.0 启动成功了

使用 node 14 的最新版本。

**Comment by fengmk2** [comment]
> > @fengmk2 node升级到 14.0.0 也不行，执行启动，会报如下错误
> > `[egg-scripts] Got error when startup: [egg-scripts] internal/modules/cjs/loader.js:1017 [egg-scripts] throw err; [egg-scripts] ^ [egg-scripts] [egg-scripts] Error: Cannot find module 'node:crypto' [egg-scripts] Require stack: [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/crypto.js [egg-scripts] - /node_modules/cluster-client/node_modules/utility/dist/commonjs/index.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/utils.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/lib/logger.js [egg-scripts] - /node_modules/cluster-client/node_modules/egg-logger/index.js [egg-scripts] - /node_modules/cluster-client/lib/default_logger.js [egg-scripts] - /node_modules/cluster-client/lib/index.js [egg-scripts] - /node_modules/cluster-client/index.js [egg-scripts] - /node_modules/egg/lib/application.js [egg-scripts] - /node_modules/egg/index.js `
> > 按照报错显示， cluster-client 依赖的第三方库 utility 2.1.0 版本需要 node >= 16.0.0 https://github.com/node-modules/utility/blob/master/package.json
> > 将node版本升级到16.0.0 启动成功了
> 
> 吐槽下：毫无预期管理，egg2.x版本只要求了node>8.5就行了，结果这又来了个node>=14?16😓

node 官方都不支持这些版本了，我们没法支持。

**Comment by zhixiangyao** [comment]
在公司的 `node` `v14.17.0` 容器里, 我也遇到了相同的问题.

```
Cannot find module 'node:crypto'
```

因为 `egg` 依赖了 `cluster-client` 并且没有锁死版本, 导致 `cluster-client` 升级到 3.7.0, 然后 `cluster-client` 的 3.7.0 版本更新了utility 到 2.1.0, 然后 utility 的 crypto.ts 里面使用了 `node:crypto`.

**Comment by fengmk2** [comment]
@zhixiangyao 更新 node 到 14 最新版本

**Comment by zhixiangyao** [comment]
> 在公司的 `node` `v14.17.0` 容器里, 我也遇到了相同的问题.
> 
> ```
> Cannot find module 'node:crypto'
> ```
> 
> 因为 `egg` 依赖了 `cluster-client` 并且没有锁死版本, 导致 `cluster-client` 升级到 `3.7.0`, 然后 `cluster-client` 的 `3.7.0` 版本更新了 `utility` 到 `2.1.0`, 然后 `utility` 的 `crypto.ts` 里面使用了 `node:crypto`.

临时解决方法: 删除 package-lock.json 后, 在 package.json 里安装了 "cluster-client": "3.5.0" 出新生成 package-lock.json 后解决了

**Comment by zcookies** [comment]
同样遇到该问题，启动报错：const traceId = ctx.tracer?.traceId || '-';  
链式可选符在 nodejs 13 以下都不支持，目前升级到 16.13.0 版本无问题。 
问题：后续的版本没有保障，目前默认锁的都是大版本号，自动升级小版本号。如果升级有环境有要求的话，是不是应该发布大版本？

**Comment by fengmk2** [comment]
> https://github.com/node-modules/cluster-client/blob/master/package.json#L58
> 
> cluster-client 只支持 node >= 14

这里已经声明 node 的版本，只需要升级到 14 最新版本即可。我们不会去支持 nodejs 官方都不支持的 nodejs 版本了。
