### ISSUE TITLE
utility@2 需要node升级

### ISSUE THREAD

**Issue by LynnHg** [node-modules/cluster-client#69]
3.7.0更新依赖了utility@2，但utility@2中使用"node:crypto"引入，该前缀引入需要node14.18.0/16.0.0支持。
因此，这里的版本更新不兼容了。
请问是否考虑在大版本去引入utility@2，例如4.0.0，而不是在3.x.x?

**Comment by fengmk2** [comment]
https://github.com/node-modules/cluster-client/blame/master/package.json

请用 14 最新版本吧，本身老版本就有安全问题

**Comment by fengmk2** [comment]
https://github.com/node-modules/cluster-client/pull/70
